# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1000, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 600))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.parse_res_tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.parse_res_tableWidget.setGeometry(QtCore.QRect(10, 190, 981, 361))
        self.parse_res_tableWidget.setRowCount(100)
        self.parse_res_tableWidget.setColumnCount(9)
        self.parse_res_tableWidget.setObjectName(_fromUtf8("parse_res_tableWidget"))
        item = QtGui.QTableWidgetItem()
        self.parse_res_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.parse_res_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.parse_res_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.parse_res_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.parse_res_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.parse_res_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.parse_res_tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.parse_res_tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.parse_res_tableWidget.setHorizontalHeaderItem(8, item)
        self.IPSearch_Button = QtGui.QPushButton(self.centralwidget)
        self.IPSearch_Button.setGeometry(QtCore.QRect(880, 20, 71, 21))
        self.IPSearch_Button.setObjectName(_fromUtf8("IPSearch_Button"))
        self.IPinput_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.IPinput_lineEdit.setGeometry(QtCore.QRect(680, 20, 191, 20))
        self.IPinput_lineEdit.setObjectName(_fromUtf8("IPinput_lineEdit"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(560, 20, 111, 20))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.Whois_res_TextEdit = QtGui.QTextEdit(self.centralwidget)
        self.Whois_res_TextEdit.setGeometry(QtCore.QRect(680, 50, 271, 121))
        self.Whois_res_TextEdit.setReadOnly(True)
        self.Whois_res_TextEdit.setObjectName(_fromUtf8("Whois_res_TextEdit"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(570, 50, 101, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 541, 161))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pathdisplay_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.pathdisplay_lineEdit.setGeometry(QtCore.QRect(10, 40, 431, 20))
        self.pathdisplay_lineEdit.setReadOnly(True)
        self.pathdisplay_lineEdit.setObjectName(_fromUtf8("pathdisplay_lineEdit"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 111, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(300, 90, 71, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(290, 110, 231, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.parsing_pushButton = QtGui.QPushButton(self.groupBox)
        self.parsing_pushButton.setGeometry(QtCore.QRect(450, 40, 75, 23))
        self.parsing_pushButton.setObjectName(_fromUtf8("parsing_pushButton"))
        self.groupBox.raise_()
        self.parse_res_tableWidget.raise_()
        self.IPSearch_Button.raise_()
        self.IPinput_lineEdit.raise_()
        self.label.raise_()
        self.Whois_res_TextEdit.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.menubar.setToolTip(_fromUtf8(""))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.parse_res_tableWidget.setSortingEnabled(False)
        item = self.parse_res_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Subject", None))
        item = self.parse_res_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "IP Address", None))
        item = self.parse_res_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Send Date", None))
        item = self.parse_res_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Recv Date", None))
        item = self.parse_res_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Contents", None))
        item = self.parse_res_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Attach File", None))
        item = self.parse_res_tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Hash", None))
        item = self.parse_res_tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Spam", None))
        item = self.parse_res_tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Malicious", None))
        self.IPSearch_Button.setText(_translate("MainWindow", "Search", None))
        self.label.setText(_translate("MainWindow", "Whois IP search :", None))
        self.label_3.setText(_translate("MainWindow", "Search results :", None))
        self.groupBox.setTitle(_translate("MainWindow", "eml parser", None))
        self.label_2.setText(_translate("MainWindow", "E-mail file path", None))
        self.label_4.setText(_translate("MainWindow", "Time zone", None))
        self.parsing_pushButton.setText(_translate("MainWindow", "Parsing", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))

